
  export enum Pkm {
    DITTO = "ditto",
    BULBASAUR = "bulbasaur",
    IVYSAUR = "ivysaur",
    VENUSAUR = "venusaur",
    CHARMANDER = "charmander",
    CHARMELEON = "charmeleon",
    CHARIZARD = "charizard",
    SQUIRTLE = "squirtle",
    WARTORTLE = "wartortle",
    BLASTOISE = "blastoise",
    GEODUDE = "geodude",
    GRAVELER = "graveler",
    GOLEM = "golem",
    AZURILL = "azurill",
    MARILL = "marill",
    AZUMARILL = "azumarill",
    ZUBAT = "zubat",
    GOLBAT = "golbat",
    CROBAT = "crobat",
    MAREEP = "mareep",
    FLAFFY = "flaffy",
    AMPHAROS = "ampharos",
    CLEFFA = "cleffa",
    CLEFAIRY = "clefairy",
    CLEFABLE = "clefable",
    IGGLYBUFF = "igglybuff",
    WIGGLYTUFF = "wygglytuff",
    JIGGLYPUFF = "jigglypuff",
    CATERPIE = "caterpie",
    METAPOD = "metapod",
    BUTTERFREE = "butterfree",
    WEEDLE = "weedle",
    KAKUNA = "kakuna",
    BEEDRILL = "beedrill",
    PIDGEY = "pidgey",
    PIDGEOTTO = "pidgeotto",
    PIDGEOT = "pidgeot",
    HOPPIP = "hoppip",
    SKIPLOOM = "skiploom",
    JUMPLUFF = "jumpluff",
    SEEDOT = "seedot",
    NUZLEAF = "nuzleaf",
    SHIFTRY = "shiftry",
    STARLY = "starly",
    STARAVIA = "staravia",
    STARAPTOR = "staraptor",
    CHIKORITA = "chikorita",
    BAYLEEF = "bayleef",
    MEGANIUM = "meganium",
    CYNDAQUIL = "cyndaquil",
    QUILAVA = "quilava",
    TYPHLOSION = "typlosion",
    TOTODILE = "totodile",
    CROCONAW = "croconaw",
    FERALIGATR = "feraligatr",
    TREECKO = "treecko",
    GROVYLE = "grovyle",
    SCEPTILE = "sceptile",
    TORCHIC = "torchic",
    COMBUSKEN = "combusken",
    BLAZIKEN = "blaziken",
    MUDKIP = "mudkip",
    MARSHTOMP = "marshtomp",
    SWAMPERT = "swampert",
    TURTWIG = "turtwig",
    GROTLE = "grotle",
    TORTERRA = "torterra",
    CHIMCHAR = "chimchar",
    MONFERNO = "monferno",
    INFERNAPE = "infernape",
    PIPLUP = "piplup",
    PRINPLUP = "prinplup",
    EMPOLEON = "empoleon",
    NIDORANF = "nidoranF",
    NIDORINA = "nidorina",
    NIDOQUEEN = "nidoqueen",
    NIDORANM = "nidoranM",
    NIDORINO = "nidorino",
    NIDOKING = "nidoking",
    PICHU = "pichu",
    PIKACHU = "pikachu",
    RAICHU = "raichu",
    MACHOP = "machop",
    MACHOKE = "machoke",
    MACHAMP = "machamp",
    HORSEA = "horsea",
    SEADRA = "seadra",
    KINGDRA = "kingdra",
    TRAPINCH = "trapinch",
    VIBRAVA = "vibrava",
    FLYGON = "flygon",
    SPHEAL = "spheal",
    SEALEO = "sealeo",
    WALREIN = "walrein",
    ARON = "aron",
    LAIRON = "lairon",
    AGGRON = "aggron",
    MAGNEMITE = "magnemite",
    MAGNETON = "magneton",
    MAGNEZONE = "magnezone",
    RHYHORN = "rhyhorn",
    RHYDON = "rhydon",
    RHYPERIOR = "rhyperior",
    TOGEPI = "togepi",
    TOGETIC = "togetic",
    TOGEKISS = "togekiss",
    DUSKULL = "duskull",
    DUSCLOPS = "dusclops",
    DUSKNOIR = "dusknoir",
    LOTAD = "lotad",
    LOMBRE = "lombre",
    LUDICOLO = "ludicolo",
    SHINX = "shinx",
    LUXIO = "luxio",
    LUXRAY = "luxray",
    POLIWAG = "poliwag",
    POLIWHIRL = "poliwhirl",
    POLITOED = "politoed",
    ABRA = "abra",
    KADABRA = "kadabra",
    ALAKAZAM = "alakazam",
    GASTLY = "gastly",
    HAUNTER = "haunter",
    GENGAR = "gengar",
    DRATINI = "dratini",
    DRAGONAIR = "dragonair",
    DRAGONITE = "dragonite",
    LARVITAR = "larvitar",
    PUPITAR = "pupitar",
    TYRANITAR = "tyranitar",
    SLAKOTH = "slakoth",
    VIGOROTH = "vigoroth",
    SLAKING = "slaking",
    RALTS = "ralts",
    KIRLIA = "kirlia",
    GARDEVOIR = "gardevoir",
    BAGON = "bagon",
    SHELGON = "shelgon",
    SALAMENCE = "salamence",
    BELDUM = "beldum",
    METANG = "metang",
    METAGROSS = "metagross",
    GIBLE = "gible",
    GABITE = "gabite",
    GARCHOMP = "garchomp",
    ELEKID = "elekid",
    ELECTABUZZ = "electabuzz",
    ELECTIVIRE = "electivire",
    MAGBY = "magby",
    MAGMAR = "magmar",
    MAGMORTAR = "magmortar",
    MUNCHLAX = "munchlax",
    SNORLAX = "snorlax",
    GROWLITHE = "growlithe",
    ARCANINE = "arcanine",
    ONIX = "onix",
    STEELIX = "steelix",
    MEGA_STEELIX = "mega-steelix",
    SCYTHER = "scyther",
    SCIZOR = "scizor",
    MEGA_SCIZOR = "mega-scizor",
    RIOLU = "riolu",
    LUCARIO = "lucario",
    MEGA_LUCARIO = "mega-lucario",
    MAGIKARP = "magikarp",
    RATTATA = "rattata",
    RATICATE = "raticate",
    SPEAROW = "spearow",
    FEAROW = "fearow",
    GYARADOS = "gyarados",
    LUGIA = "lugia",
    GIRATINA = "giratina",
    ZAPDOS = "zapdos",
    MOLTRES = "moltres",
    ARTICUNO = "articuno",
    DIALGA = "dialga",
    PALKIA = "palkia",
    SUICUNE = "suicune",
    RAIKOU = "raikou",
    ENTEI = "entei",
    REGICE = "regice",
    REGIROCK = "regirock",
    REGISTEEL = "registeel",
    KYOGRE = "kyogre",
    GROUDON = "groudon",
    RAYQUAZA = "rayquaza",
    REGIGIGAS = "regigigas",
    EEVEE = "eevee",
    VAPOREON = "vaporeon",
    JOLTEON = "jolteon",
    FLAREON = "flareon",
    ESPEON = "espeon",
    UMBREON = "umbreon",
    LEAFEON = "leafeon",
    SYLVEON = "sylveon",
    MEDITITE = "meditite",
    MEDICHAM = "medicham",
    MEGA_MEDICHAM = "mega-medicham",
    NUMEL = "numel",
    CAMERUPT = "camerupt",
    MEGA_CAMERUPT = "mega-camerupt",
    DARKRAI = "darkrai",
    LITWICK = "litwick",
    LAMPENT = "lampent",
    CHANDELURE = "chandelure",
    SLOWPOKE = "slowpoke",
    SLOWBRO = "slowbro",
    SLOWKING = "slowking",
    BELLSPROUT = "bellsprout",
    WEEPINBELL = "weepinbell",
    VICTREEBEL = "victreebel",
    CARVANHA = "carvanha",
    SWINUB = "swinub",
    PILOSWINE = "piloswine",
    MAMOSWINE = "mamoswine",
    SNORUNT = "snorunt",
    GLALIE = "glalie",
    FROSLASS = "froslass",
    SNOVER = "snover",
    ABOMASNOW = "abomasnow",
    MEGA_ABOMASNOW = "mega-abomasnow",
    VANILLITE = "vanillite",
    VANILLISH = "vanillish",
    VANILLUXE = "vanilluxe",
    GLACEON = "glaceon",
    VOLCARONA = "volcarona",
    LANDORUS = "landorus",
    THUNDURUS = "thundurus",
    TORNADUS = "tornadus",
    KELDEO = "keldeo",
    TERRAKION = "terrakion",
    VIRIZION = "virizion",
    COBALION = "cobalion",
    MANAPHY = "manaphy",
    ROTOM = "rotom",
    SPIRITOMB = "spiritomb",
    ABSOL = "absol",
    LAPRAS = "lapras",
    LATIAS = "latias",
    LATIOS = "latios",
    MESPRIT = "mesprit",
    AZELF = "azelf",
    UXIE = "uxie",
    MEWTWO = "mewtwo",
    KYUREM = "kyurem",
    RESHIRAM = "reshiram",
    ZEKROM = "zekrom",
    CELEBI = "celebi",
    VICTINI = "victini",
    JIRACHI = "jirachi",
    ARCEUS = "arceus",
    DEOXYS = "deoxys",
    SHAYMIN = "shaymin",
    CRESSELIA = "cresselia",
    HEATRAN = "heatran",
    HO_OH = "ho-Oh",
    AERODACTYL = "aerodactyl",
    PRIMAL_KYOGRE = "primal-Kyogre",
    PRIMAL_GROUDON = "primal-Groudon",
    MEOWTH = "meowth",
    PERSIAN = "persian",
    DEINO = "deino",
    ZWEILOUS = "zweilous",
    HYDREIGON = "hydreigon",
    SANDILE = "sandile",
    KROKOROK = "krokorok",
    KROOKODILE = "krookodile",
    SOLOSIS = "solosis",
    DUOSION = "duosion",
    REUNICLUS = "reuniclus",
    MEGA_RAYQUAZA = "mega-Rayquaza",
    SWABLU = "swablu",
    ODDISH = "oddish",
    GLOOM = "gloom",
    VILEPLUME = "vileplume",
    BELLOSSOM = "bellossom",
    AMAURA = "amaura",
    AURORUS = "aurorus",
    ANORITH = "anorith",
    ARMALDO = "armaldo",
    ARCHEN = "archen",
    ARCHEOPS = "archeops",
    SHIELDON = "shieldon",
    BASTIODON = "bastiodon",
    TIRTOUGA = "tirtouga",
    CARRACOSTA = "carracosta",
    LILEEP = "lileep",
    CRADILY = "cradily",
    CRANIDOS = "cranidos",
    RAMPARDOS = "rampardos",
    KABUTO = "kabuto",
    KABUTOPS = "kabutops",
    OMANYTE = "omanyte",
    OMASTAR = "omastar",
    TYRUNT = "tyrunt",
    TYRANTRUM = "tyrantrum",
    BUDEW = "budew",
    ROSELIA = "roselia",
    ROSERADE = "roserade",
    BUNEARY = "buneary",
    LOPUNNY = "lopunny",
    MEGA_LOPUNNY = "mega-lopunny",
    AXEW = "axew",
    FRAXURE = "fraxure",
    HAXORUS = "haxorus",
    VENIPEDE = "venipede",
    WHIRLIPEDE = "whirlipede",
    SCOLIPEDE = "scolipede",
    PORYGON = "porygon",
    PORYGON_2 = "porygon2",
    PORYGON_Z = "porygon-z",
    ELECTRIKE = "electrike",
    MANECTRIC = "manectric",
    MEGA_MANECTRIC = "mega-manectric",
    SHUPPET = "shuppet",
    BANETTE = "banette",
    MEGA_BANETTE = "mega-banette",
    HONEDGE = "honedge",
    DOUBLADE = "doublade",
    AEGISLASH = "aegislash",
    CUBONE = "cubone",
    MAROWAK = "marowak",
    ALOLAN_MAROWAK = "alolan-marowak",
    WHISMUR = "whismur",
    LOUDRED = "loudred",
    EXPLOUD = "exploud",
    TYMPOLE = "tympole",
    PALPITOAD = "palpitoad",
    SEISMITOAD = "seismitoad",
    SEWADDLE = "sewaddle",
    SWADLOON = "swadloon",
    LEAVANNY = "leavanny",
    PIKIPEK = "pikipek",
    TRUMBEAK = "trumbeak",
    TOUCANNON = "toucannon",
    FLABEBE = "flabebe",
    FLOETTE = "floette",
    FLORGES = "florges",
    JANGMO_O = "jangmo-o",
    HAKAMO_O = "hakamo-o",
    KOMMO_O = "kommo-o",
    MELOETTA = "meloetta",
    ALTARIA = "altaria",
    MEGA_ALTARIA = "mega-altaria",
    CASTFORM = "castform",
    CASTFORM_SUN = "castform-sun",
    CASTFORM_RAIN = "castform-rain",
    CASTFORM_HAIL = "castform-hail",
    CORPHISH = "corphish",
    CRAWDAUNT = "crawdaunt",
    JOLTIK = "joltik",
    GALVANTULA = "galvantula",
    GENESECT = "genesect",
    RELICANTH = "relicanth",
    DIANCIE = "diancie",
    HATENNA = "hatenna",
    HATTREM = "hattrem",
    HATTERENE = "hatterene",
    FENNEKIN = "fennekin",
    BRAIXEN = "braixen",
    DELPHOX = "delphox",
    MAKUHITA = "makuhita",
    HARIYAMA = "hariyama",
    REGIELEKI = "regieleki",
    REGIDRAGO = "regidrago",
    GUZZLORD = "guzzlord",
    ETERNATUS = "eternatus",
    PONYTA = "ponyta",
    RAPIDASH = "rapidash",
    NINCADA = "nincada",
    NINJASK = "ninjask",
    SHEDNINJA = "shedninja",
    NOIBAT = "noibat",
    NOIVERN = "noivern",
    PUMPKABOO = "pumpkaboo",
    GOURGEIST = "gourgeist",
    CACNEA = "cacnea",
    CACTURNE = "cacturne",
    TAUROS = "tauros",
    DEFAULT = "default",
    HAPPINY = "happiny",
    CHANSEY = "chansey",
    BLISSEY = "blissey",
    TAPU_KOKO = "tapu-koko",
    TAPU_LELE = "tapu-lele",
    STAKATAKA = "stakataka",
    BLACEPHALON = "blacephalon",
    HOUNDOUR = "houndour",
    HOUNDOOM = "houndoom",
    MEGA_HOUNDOOM = "mega-houndoom",
    CLAMPERL = "clamperl",
    HUNTAIL = "huntail",
    GOREBYSS = "gorebyss",
    SMOOCHUM = "smoochum",
    JYNX = "jynx",
    SALANDIT = "salandit",
    SALAZZLE = "salazzle",
    VENONAT = "venonat",
    VENOMOTH = "venomoth",
    VOLTORB = "voltorb",
    ELECTRODE = "electrode",
    SLUGMA = "slugma",
    MAGCARGO = "magcargo",
    SNEASEL = "sneasel",
    WEAVILE = "weavile",
    CROAGUNK = "croagunk",
    TOXICROAK = "toxicroak",
    CHINCHOU = "chinchou",
    LANTURN = "lanturn",
    POOCHYENA = "poochyena",
    MIGHTYENA = "mightyena",
    BRONZOR = "bronzor",
    BRONZONG = "bronzong",
    DRIFLOON = "drifloon",
    DRIFBLIM = "drifblim",
    SHROOMISH = "shroomish",
    BRELOOM = "breloom",
    TENTACOOL = "tentacool",
    TENTACRUEL = "tentacruel",
    SNUBULL = "snubull",
    GRANBULL = "granbull",
  }
  
  export const PkmIndex: { [key in Pkm]: string } = {
    [Pkm.DEFAULT]: "0000",
    [Pkm.DITTO]: "0132",
    [Pkm.BULBASAUR]: "0001",
    [Pkm.IVYSAUR]: "0002",
    [Pkm.VENUSAUR]: "0003",
    [Pkm.CHARMANDER]: "0004",
    [Pkm.CHARMELEON]: "0005",
    [Pkm.CHARIZARD]: "0006",
    [Pkm.SQUIRTLE]: "0007",
    [Pkm.WARTORTLE]: "0008",
    [Pkm.BLASTOISE]: "0009",
    [Pkm.GEODUDE]: "0074",
    [Pkm.GRAVELER]: "0075",
    [Pkm.GOLEM]: "0076",
    [Pkm.AZURILL]: "0298",
    [Pkm.MARILL]: "0183",
    [Pkm.AZUMARILL]: "0184",
    [Pkm.ZUBAT]: "0041",
    [Pkm.GOLBAT]: "0042",
    [Pkm.CROBAT]: "0169",
    [Pkm.MAREEP]: "0179",
    [Pkm.FLAFFY]: "0180",
    [Pkm.AMPHAROS]: "0181",
    [Pkm.CLEFFA]: "0173",
    [Pkm.CLEFAIRY]: "0035",
    [Pkm.CLEFABLE]: "0036",
    [Pkm.IGGLYBUFF]: "0174",
    [Pkm.WIGGLYTUFF]: "0040",
    [Pkm.JIGGLYPUFF]: "0039",
    [Pkm.CATERPIE]: "0010",
    [Pkm.METAPOD]: "0011",
    [Pkm.BUTTERFREE]: "0012",
    [Pkm.WEEDLE]: "0013",
    [Pkm.KAKUNA]: "0014",
    [Pkm.BEEDRILL]: "0015",
    [Pkm.PIDGEY]: "0016",
    [Pkm.PIDGEOTTO]: "0017",
    [Pkm.PIDGEOT]: "0018",
    [Pkm.HOPPIP]: "0187",
    [Pkm.SKIPLOOM]: "0188",
    [Pkm.JUMPLUFF]: "0189",
    [Pkm.SEEDOT]: "0273",
    [Pkm.NUZLEAF]: "0274",
    [Pkm.SHIFTRY]: "0275",
    [Pkm.STARLY]: "0396",
    [Pkm.STARAVIA]: "0397",
    [Pkm.STARAPTOR]: "0398",
    [Pkm.CHIKORITA]: "0152",
    [Pkm.BAYLEEF]: "0153",
    [Pkm.MEGANIUM]: "0154",
    [Pkm.CYNDAQUIL]: "0155",
    [Pkm.QUILAVA]: "0156",
    [Pkm.TYPHLOSION]: "0157",
    [Pkm.TOTODILE]: "0158",
    [Pkm.CROCONAW]: "0159",
    [Pkm.FERALIGATR]: "0160",
    [Pkm.TREECKO]: "0252",
    [Pkm.GROVYLE]: "0253",
    [Pkm.SCEPTILE]: "0254",
    [Pkm.TORCHIC]: "0255",
    [Pkm.COMBUSKEN]: "0256",
    [Pkm.BLAZIKEN]: "0257",
    [Pkm.MUDKIP]: "0258",
    [Pkm.MARSHTOMP]: "0259",
    [Pkm.SWAMPERT]: "0260",
    [Pkm.TURTWIG]: "0387",
    [Pkm.GROTLE]: "0388",
    [Pkm.TORTERRA]: "0389",
    [Pkm.CHIMCHAR]: "0390",
    [Pkm.MONFERNO]: "0391",
    [Pkm.INFERNAPE]: "0392",
    [Pkm.PIPLUP]: "0393",
    [Pkm.PRINPLUP]: "0394",
    [Pkm.EMPOLEON]: "0395",
    [Pkm.NIDORANF]: "0029",
    [Pkm.NIDORINA]: "0030",
    [Pkm.NIDOQUEEN]: "0031",
    [Pkm.NIDORANM]: "0032",
    [Pkm.NIDORINO]: "0033",
    [Pkm.NIDOKING]: "0034",
    [Pkm.PICHU]: "0172",
    [Pkm.PIKACHU]: "0025",
    [Pkm.RAICHU]: "0026",
    [Pkm.MACHOP]: "0066",
    [Pkm.MACHOKE]: "0067",
    [Pkm.MACHAMP]: "0068",
    [Pkm.HORSEA]: "0116",
    [Pkm.SEADRA]: "0117",
    [Pkm.KINGDRA]: "0230",
    [Pkm.TRAPINCH]: "0328",
    [Pkm.VIBRAVA]: "0329",
    [Pkm.FLYGON]: "0330",
    [Pkm.SPHEAL]: "0363",
    [Pkm.SEALEO]: "0364",
    [Pkm.WALREIN]: "0365",
    [Pkm.ARON]: "0304",
    [Pkm.LAIRON]: "0305",
    [Pkm.AGGRON]: "0306",
    [Pkm.MAGNEMITE]: "0081",
    [Pkm.MAGNETON]: "0082",
    [Pkm.MAGNEZONE]: "0462",
    [Pkm.RHYHORN]: "0111",
    [Pkm.RHYDON]: "0112",
    [Pkm.RHYPERIOR]: "0464",
    [Pkm.TOGEPI]: "0175",
    [Pkm.TOGETIC]: "0176",
    [Pkm.TOGEKISS]: "0468",
    [Pkm.DUSKULL]: "0355",
    [Pkm.DUSCLOPS]: "0356",
    [Pkm.DUSKNOIR]: "0477",
    [Pkm.LOTAD]: "0270",
    [Pkm.LOMBRE]: "0271",
    [Pkm.LUDICOLO]: "0272",
    [Pkm.SHINX]: "0403",
    [Pkm.LUXIO]: "0404",
    [Pkm.LUXRAY]: "0405",
    [Pkm.POLIWAG]: "0060",
    [Pkm.POLIWHIRL]: "0061",
    [Pkm.POLITOED]: "0186",
    [Pkm.ABRA]: "0063",
    [Pkm.KADABRA]: "0064",
    [Pkm.ALAKAZAM]: "0065",
    [Pkm.GASTLY]: "0092",
    [Pkm.HAUNTER]: "0093",
    [Pkm.GENGAR]: "0094",
    [Pkm.DRATINI]: "0147",
    [Pkm.DRAGONAIR]: "0148",
    [Pkm.DRAGONITE]: "0149",
    [Pkm.LARVITAR]: "0246",
    [Pkm.PUPITAR]: "0247",
    [Pkm.TYRANITAR]: "0248",
    [Pkm.SLAKOTH]: "0287",
    [Pkm.VIGOROTH]: "0288",
    [Pkm.SLAKING]: "0289",
    [Pkm.RALTS]: "0280",
    [Pkm.KIRLIA]: "0281",
    [Pkm.GARDEVOIR]: "0282",
    [Pkm.BAGON]: "0371",
    [Pkm.SHELGON]: "0372",
    [Pkm.SALAMENCE]: "0373",
    [Pkm.BELDUM]: "0374",
    [Pkm.METANG]: "0375",
    [Pkm.METAGROSS]: "0376",
    [Pkm.GIBLE]: "0443",
    [Pkm.GABITE]: "0444",
    [Pkm.GARCHOMP]: "0445",
    [Pkm.ELEKID]: "0239",
    [Pkm.ELECTABUZZ]: "0125",
    [Pkm.ELECTIVIRE]: "0466",
    [Pkm.MAGBY]: "0240",
    [Pkm.MAGMAR]: "0126",
    [Pkm.MAGMORTAR]: "0467",
    [Pkm.MUNCHLAX]: "0446",
    [Pkm.SNORLAX]: "0143",
    [Pkm.GROWLITHE]: "0058",
    [Pkm.ARCANINE]: "0059",
    [Pkm.ONIX]: "0095",
    [Pkm.STEELIX]: "0208",
    [Pkm.MEGA_STEELIX]: "0208-0001",
    [Pkm.SCYTHER]: "0123",
    [Pkm.SCIZOR]: "0212",
    [Pkm.MEGA_SCIZOR]: "0212-0001",
    [Pkm.RIOLU]: "0447",
    [Pkm.LUCARIO]: "0448",
    [Pkm.MEGA_LUCARIO]: "0448-0001",
    [Pkm.MAGIKARP]: "0129",
    [Pkm.RATTATA]: "0019",
    [Pkm.RATICATE]: "0020",
    [Pkm.SPEAROW]: "0021",
    [Pkm.FEAROW]: "0022",
    [Pkm.GYARADOS]: "0130",
    [Pkm.LUGIA]: "0249",
    [Pkm.GIRATINA]: "0487",
    [Pkm.ZAPDOS]: "0145",
    [Pkm.MOLTRES]: "0146",
    [Pkm.ARTICUNO]: "0144",
    [Pkm.DIALGA]: "0483",
    [Pkm.PALKIA]: "0484",
    [Pkm.SUICUNE]: "0245",
    [Pkm.RAIKOU]: "0243",
    [Pkm.ENTEI]: "0244",
    [Pkm.REGICE]: "0378",
    [Pkm.REGIROCK]: "0377",
    [Pkm.REGISTEEL]: "0379",
    [Pkm.KYOGRE]: "0382",
    [Pkm.GROUDON]: "0383",
    [Pkm.RAYQUAZA]: "0384",
    [Pkm.REGIGIGAS]: "0486",
    [Pkm.EEVEE]: "0133",
    [Pkm.VAPOREON]: "0134",
    [Pkm.JOLTEON]: "0135",
    [Pkm.FLAREON]: "0136",
    [Pkm.ESPEON]: "0196",
    [Pkm.UMBREON]: "0197",
    [Pkm.LEAFEON]: "0470",
    [Pkm.SYLVEON]: "0700",
    [Pkm.MEDITITE]: "0307",
    [Pkm.MEDICHAM]: "0308",
    [Pkm.MEGA_MEDICHAM]: "0308-0001",
    [Pkm.NUMEL]: "0322",
    [Pkm.CAMERUPT]: "0323",
    [Pkm.MEGA_CAMERUPT]: "0323-0001",
    [Pkm.DARKRAI]: "0491",
    [Pkm.LITWICK]: "0607",
    [Pkm.LAMPENT]: "0608",
    [Pkm.CHANDELURE]: "0609",
    [Pkm.SLOWPOKE]: "0079",
    [Pkm.SLOWBRO]: "0080",
    [Pkm.SLOWKING]: "0199",
    [Pkm.BELLSPROUT]: "0069",
    [Pkm.WEEPINBELL]: "0070",
    [Pkm.VICTREEBEL]: "0071",
    [Pkm.CARVANHA]: "0318",
    [Pkm.SWINUB]: "0220",
    [Pkm.PILOSWINE]: "0221",
    [Pkm.MAMOSWINE]: "0473",
    [Pkm.SNORUNT]: "0361",
    [Pkm.GLALIE]: "0362",
    [Pkm.FROSLASS]: "0478",
    [Pkm.SNOVER]: "0459",
    [Pkm.ABOMASNOW]: "0460",
    [Pkm.MEGA_ABOMASNOW]: "0460-0001",
    [Pkm.VANILLITE]: "0582",
    [Pkm.VANILLISH]: "0583",
    [Pkm.VANILLUXE]: "0584",
    [Pkm.GLACEON]: "0471",
    [Pkm.VOLCARONA]: "0637",
    [Pkm.LANDORUS]: "0645",
    [Pkm.THUNDURUS]: "0642",
    [Pkm.TORNADUS]: "0641",
    [Pkm.KELDEO]: "0647",
    [Pkm.TERRAKION]: "0639",
    [Pkm.VIRIZION]: "0640",
    [Pkm.COBALION]: "0638",
    [Pkm.MANAPHY]: "0490",
    [Pkm.ROTOM]: "0479",
    [Pkm.SPIRITOMB]: "0442",
    [Pkm.ABSOL]: "0359",
    [Pkm.LAPRAS]: "0131",
    [Pkm.LATIAS]: "0380",
    [Pkm.LATIOS]: "0381",
    [Pkm.MESPRIT]: "0481",
    [Pkm.AZELF]: "0482",
    [Pkm.UXIE]: "0480",
    [Pkm.MEWTWO]: "0150",
    [Pkm.KYUREM]: "0646",
    [Pkm.RESHIRAM]: "0643",
    [Pkm.ZEKROM]: "0644",
    [Pkm.CELEBI]: "0251",
    [Pkm.VICTINI]: "0494",
    [Pkm.JIRACHI]: "0385",
    [Pkm.ARCEUS]: "0493",
    [Pkm.DEOXYS]: "0386",
    [Pkm.SHAYMIN]: "0492",
    [Pkm.CRESSELIA]: "0488",
    [Pkm.HEATRAN]: "0485",
    [Pkm.HO_OH]: "0250",
    [Pkm.AERODACTYL]: "0142",
    [Pkm.PRIMAL_KYOGRE]: "0382-0001",
    [Pkm.PRIMAL_GROUDON]: "0383-0001",
    [Pkm.MEOWTH]: "0052",
    [Pkm.PERSIAN]: "0053",
    [Pkm.DEINO]: "0633",
    [Pkm.ZWEILOUS]: "0634",
    [Pkm.HYDREIGON]: "0635",
    [Pkm.SANDILE]: "0551",
    [Pkm.KROKOROK]: "0552",
    [Pkm.KROOKODILE]: "0553",
    [Pkm.SOLOSIS]: "0577",
    [Pkm.DUOSION]: "0578",
    [Pkm.REUNICLUS]: "0579",
    [Pkm.MEGA_RAYQUAZA]: "0384-0001",
    [Pkm.SWABLU]: "0333",
    [Pkm.ODDISH]: "0043",
    [Pkm.GLOOM]: "0044",
    [Pkm.VILEPLUME]: "0045",
    [Pkm.BELLOSSOM]: "0182",
    [Pkm.AMAURA]: "0698",
    [Pkm.AURORUS]: "0699",
    [Pkm.ANORITH]: "0347",
    [Pkm.ARMALDO]: "0348",
    [Pkm.ARCHEN]: "0566",
    [Pkm.ARCHEOPS]: "0567",
    [Pkm.SHIELDON]: "0410",
    [Pkm.BASTIODON]: "0411",
    [Pkm.TIRTOUGA]: "0564",
    [Pkm.CARRACOSTA]: "0565",
    [Pkm.LILEEP]: "0345",
    [Pkm.CRADILY]: "0346",
    [Pkm.CRANIDOS]: "0408",
    [Pkm.RAMPARDOS]: "0409",
    [Pkm.KABUTO]: "0140",
    [Pkm.KABUTOPS]: "0141",
    [Pkm.OMANYTE]: "0138",
    [Pkm.OMASTAR]: "0139",
    [Pkm.TYRUNT]: "0696",
    [Pkm.TYRANTRUM]: "0697",
    [Pkm.BUDEW]: "0406",
    [Pkm.ROSELIA]: "0315",
    [Pkm.ROSERADE]: "0407",
    [Pkm.BUNEARY]: "0427",
    [Pkm.LOPUNNY]: "0428",
    [Pkm.MEGA_LOPUNNY]: "0428-0001",
    [Pkm.AXEW]: "0610",
    [Pkm.FRAXURE]: "0611",
    [Pkm.HAXORUS]: "0612",
    [Pkm.VENIPEDE]: "0543",
    [Pkm.WHIRLIPEDE]: "0544",
    [Pkm.SCOLIPEDE]: "0545",
    [Pkm.PORYGON]: "0137",
    [Pkm.PORYGON_2]: "0233",
    [Pkm.PORYGON_Z]: "0474",
    [Pkm.ELECTRIKE]: "0309",
    [Pkm.MANECTRIC]: "0310",
    [Pkm.MEGA_MANECTRIC]: "0310-0001",
    [Pkm.SHUPPET]: "0353",
    [Pkm.BANETTE]: "0354",
    [Pkm.MEGA_BANETTE]: "0354-0001",
    [Pkm.HONEDGE]: "0679",
    [Pkm.DOUBLADE]: "0680",
    [Pkm.AEGISLASH]: "0681",
    [Pkm.CUBONE]: "0104",
    [Pkm.MAROWAK]: "0105",
    [Pkm.ALOLAN_MAROWAK]: "0105-0001",
    [Pkm.WHISMUR]: "0293",
    [Pkm.LOUDRED]: "0294",
    [Pkm.EXPLOUD]: "0295",
    [Pkm.TYMPOLE]: "0535",
    [Pkm.PALPITOAD]: "0536",
    [Pkm.SEISMITOAD]: "0537",
    [Pkm.SEWADDLE]: "0540",
    [Pkm.SWADLOON]: "0541",
    [Pkm.LEAVANNY]: "0542",
    [Pkm.PIKIPEK]: "0731",
    [Pkm.TRUMBEAK]: "0732",
    [Pkm.TOUCANNON]: "0733",
    [Pkm.FLABEBE]: "0669",
    [Pkm.FLOETTE]: "0670",
    [Pkm.FLORGES]: "0671",
    [Pkm.JANGMO_O]: "0782",
    [Pkm.HAKAMO_O]: "0783",
    [Pkm.KOMMO_O]: "0784",
    [Pkm.MELOETTA]: "0648",
    [Pkm.ALTARIA]: "0334",
    [Pkm.MEGA_ALTARIA]: "0334-0001",
    [Pkm.CASTFORM]: "0351",
    [Pkm.CASTFORM_SUN]: "0351-0001",
    [Pkm.CASTFORM_RAIN]: "0351-0002",
    [Pkm.CASTFORM_HAIL]: "0351-0003",
    [Pkm.CORPHISH]: "0341",
    [Pkm.CRAWDAUNT]: "0342",
    [Pkm.JOLTIK]: "0595",
    [Pkm.GALVANTULA]: "0596",
    [Pkm.GENESECT]: "0649",
    [Pkm.RELICANTH]: "0369",
    [Pkm.DIANCIE]: "0719",
    [Pkm.HATENNA]: "0856",
    [Pkm.HATTREM]: "0857",
    [Pkm.HATTERENE]: "0858",
    [Pkm.FENNEKIN]: "0653",
    [Pkm.BRAIXEN]: "0654",
    [Pkm.DELPHOX]: "0655",
    [Pkm.MAKUHITA]: "0296",
    [Pkm.HARIYAMA]: "0297",
    [Pkm.REGIELEKI]: "0894",
    [Pkm.REGIDRAGO]: "0895",
    [Pkm.GUZZLORD]: "0799",
    [Pkm.ETERNATUS]: "0890",
    [Pkm.NOIBAT]: "0714",
    [Pkm.NOIVERN]: "0715",
    [Pkm.PUMPKABOO]: "0710",
    [Pkm.GOURGEIST]: "0711",
    [Pkm.NINCADA]: "0290",
    [Pkm.NINJASK]: "0291",
    [Pkm.SHEDNINJA]: "0292",
    [Pkm.PONYTA]: "0077",
    [Pkm.RAPIDASH]: "0078",
    cacnea: "0331",
    cacturne: "0332",
    tauros: "0128",
    happiny: "0440",
    chansey: "0113",
    blissey: "0242",
    [Pkm.TAPU_KOKO]: "0785",
    [Pkm.TAPU_LELE]: "0786",
    [Pkm.STAKATAKA]: "0805",
    [Pkm.BLACEPHALON]: "0806",
    [Pkm.HOUNDOUR]: "0228",
    [Pkm.HOUNDOOM]: "0229",
    [Pkm.MEGA_HOUNDOOM]: "0229-0001",
    [Pkm.CLAMPERL]: "0366",
    [Pkm.HUNTAIL]: "0367",
    [Pkm.GOREBYSS]: "0368",
    smoochum: "0238",
    jynx: "0124",
    salandit: "0757",
    salazzle: "0758",
    venonat: "0048",
    venomoth: "0049",
    voltorb: "0100",
    electrode: "0101",
    slugma: "0218",
    magcargo: "0219",
    sneasel: "0215",
    weavile: "0461",
    croagunk: "0453",
    toxicroak: "0454",
    chinchou: "0170",
    lanturn: "0171",
    poochyena: "0261",
    mightyena: "0262",
    bronzor: "0436",
    bronzong: "0437",
    drifloon: "0425",
    drifblim: "0426",
    shroomish: "0285",
    breloom: "0286",
    tentacool: "0072",
    tentacruel: "0073",
    snubull: "0209",
    granbull: "0210",
  }

export enum Header {
    WALL = "WALL",
    WALL_ALT_1 = "WALL_ALT_1",
    WALL_ALT_2 = "WALL_ALT_2",
    WALL_ALT_3 = "WALL_ALT_3",
    GROUND = "GROUND",
    GROUND_ALT_1 = "GROUND_ALT_1",
    GROUND_ALT_2 = "GROUND_ALT_2",
    GROUND_ALT_3 = "GROUND_ALT_3",
    GROUND_ALT_4 = "GROUND_ALT_4",
    WATER = "WATER",
    ABYSS = "ABYSS",
    ABYSS_ALT_1 = "ABYSS_ALT_1",
    ABYSS_ALT_2 = "ABYSS_ALT_2"
  }
  
  export const MaskCoordinate: { [key in Mask]: { x: number; y: number } } =
    Object.freeze({
      X: { x: 1, y: 4 },
      A: { x: 1, y: 8 },
      B: { x: 0, y: 7 },
      C: { x: 1, y: 6 },
      D: { x: 2, y: 7 },
      AB: { x: 0, y: 5 },
      AC: { x: 0, y: 4 },
      AD: { x: 2, y: 5 },
      BC: { x: 0, y: 3 },
      BD: { x: 1, y: 3 },
      CD: { x: 2, y: 3 },
      ABC: { x: 0, y: 10 },
      ABD: { x: 1, y: 11 },
      ACD: { x: 2, y: 10 },
      BCD: { x: 1, y: 9 },
      ABCD: { x: 1, y: 7 },
      A1B: { x: 0, y: 2 },
      B2C: { x: 0, y: 0 },
      C3D: { x: 2, y: 0 },
      AD4: { x: 2, y: 2 },
      A1BC: { x: 0, y: 17 },
      AB2C: { x: 0, y: 18 },
      B2CD: { x: 1, y: 19 },
      BC3D: { x: 0, y: 19 },
      AC3D: { x: 1, y: 18 },
      ACD4: { x: 1, y: 17 },
      A1BD: { x: 1, y: 20 },
      ABD4: { x: 0, y: 20 },
      A1B2C: { x: 0, y: 1 },
      B2C3D: { x: 1, y: 0 },
      AC3D4: { x: 2, y: 1 },
      A1BD4: { x: 1, y: 2 },
      A1BCD: { x: 0, y: 22 },
      AB2CD: { x: 0, y: 21 },
      ABC3D: { x: 1, y: 21 },
      ABCD4: { x: 1, y: 22 },
      A1B2CD: { x: 2, y: 13 },
      AB2C3D: { x: 1, y: 14 },
      ABC3D4: { x: 0, y: 13 },
      A1BCD4: { x: 1, y: 12 },
      A1B2C3D: { x: 1, y: 16 },
      AB2C3D4: { x: 0, y: 16 },
      A1BC3D4: { x: 0, y: 15 },
      A1B2CD4: { x: 1, y: 15 },
      A1BC3D: { x: 0, y: 23 },
      AB2CD4: { x: 1, y: 23 },
      A1B2C3D4: { x: 1, y: 1 }
    })
  
  export enum Mask {
    X = "X",
    A = "A",
    B = "B",
    C = "C",
    D = "D",
    AB = "AB",
    AC = "AC",
    AD = "AD",
    BC = "BC",
    BD = "BD",
    CD = "CD",
    ABC = "ABC",
    ABD = "ABD",
    ACD = "ACD",
    BCD = "BCD",
    ABCD = "ABCD",
    A1B = "A1B",
    B2C = "B2C",
    C3D = "C3D",
    AD4 = "AD4",
    A1BC = "A1BC",
    AB2C = "AB2C",
    B2CD = "B2CD",
    BC3D = "BC3D",
    AC3D = "AC3D",
    ACD4 = "ACD4",
    A1BD = "A1BD",
    ABD4 = "ABD4",
    A1B2C = "A1B2C",
    B2C3D = "B2C3D",
    AC3D4 = "AC3D4",
    A1BD4 = "A1BD4",
    A1BCD = "A1BCD",
    AB2CD = "AB2CD",
    ABC3D = "ABC3D",
    ABCD4 = "ABCD4",
    A1B2CD = "A1B2CD",
    AB2C3D = "AB2C3D",
    ABC3D4 = "ABC3D4",
    A1BCD4 = "A1BCD4",
    A1B2C3D = "A1B2C3D",
    AB2C3D4 = "AB2C3D4",
    A1BC3D4 = "A1BC3D4",
    A1B2CD4 = "A1B2CD4",
    A1BC3D = "A1BC3D",
    AB2CD4 = "AB2CD4",
    A1B2C3D4 = "A1B2C3D4"
  }
  
  export enum TerrainType {
    GROUND,
    WALL,
    WATER
  }
  
  export const IdTable: { [key: number]: Mask } = {
    0: Mask.X,
    1: Mask.A,
    2: Mask.B,
    4: Mask.C,
    8: Mask.D,
    3: Mask.AB,
    5: Mask.AC,
    9: Mask.AD,
    6: Mask.BC,
    10: Mask.BD,
    12: Mask.CD,
    7: Mask.ABC,
    11: Mask.ABD,
    13: Mask.ACD,
    14: Mask.BCD,
    15: Mask.ABCD,
    19: Mask.A1B,
    38: Mask.B2C,
    76: Mask.C3D,
    137: Mask.AD4,
    23: Mask.A1BC,
    39: Mask.AB2C,
    46: Mask.B2CD,
    78: Mask.BC3D,
    77: Mask.AC3D,
    141: Mask.ACD4,
    27: Mask.A1BD,
    139: Mask.ABD4,
    55: Mask.A1B2C,
    110: Mask.B2C3D,
    205: Mask.AC3D4,
    155: Mask.A1BD4,
    31: Mask.A1BCD,
    47: Mask.AB2CD,
    79: Mask.ABC3D,
    143: Mask.ABCD4,
    63: Mask.A1B2CD,
    111: Mask.AB2C3D,
    207: Mask.ABC3D4,
    159: Mask.A1BCD4,
    127: Mask.A1B2C3D,
    239: Mask.AB2C3D4,
    223: Mask.A1BC3D4,
    191: Mask.A1B2CD4,
    95: Mask.A1BC3D,
    175: Mask.AB2CD4,
    255: Mask.A1B2C3D4
  }

  export enum Dungeon {
    FOURTH_STATION_PATH = "FOURTH_STATION_PATH",
    SEVEN_STATION_PATH = "SEVEN_STATION_PATH",
    BARREN_VALLEY = "BARREN_VALLEY",
    DARK_ICE_MOUNTAIN_PEAK = "DARK_ICE_MOUNTAIN_PEAK",
    DARK_WASTELAND = "DARK_WASTELAND",
    DEEP_BOULDER_QUARRY = "DEEP_BOULDER_QUARRY",
    LIMESTONE_CAVERN = "LIMESTONE_CAVERN",
    DEEP_LIMESTONE_CAVERN = "DEEP_LIMESTONE_CAVERN",
    ICICLE_FOREST = "ICICLE_FOREST",
    MURKY_FOREST = "MURKY_FOREST",
    SPACIAL_CLIFFS = "SPACIAL_CLIFFS",
    TEMPORAL_SPIRE_FUTURE = "TEMPORAL_SPIRE_FUTURE",
    TEMPORAL_TOWER_FUTURE = "TEMPORAL_TOWER_FUTURE",
    VAST_ICE_MOUNTAIN_PEAK = "VAST_ICE_MOUNTAIN_PEAK",
    VAST_ICE_MOUNTAIN = "VAST_ICE_MOUNTAIN",
    AMP_PLAINS = "AMP_PLAINS",
    FAR_AMP_PLAINS = "FAR_AMP_PLAINS",
    FINAL_MAZE_B23F = "FINAL_MAZE_B23F",
    FOGGY_FOREST = "FOGGY_FOREST",
    FOREST_PATH = "FOREST_PATH",
    GOLD_CHAMBER = "GOLD_CHAMBER",
    HIDDEN_HIGHLAND = "HIDDEN_HIGHLAND",
    MYSTERY_JUNGLE_01F_15F = "MYSTERY_JUNGLE_01F_15F",
    MYSTERY_JUNGLE_16F_30F = "MYSTERY_JUNGLE_16F_30F",
    MYSTIFYING_FOREST = "MYSTIFYING_FOREST",
    BEACH_CAVE = "BEACH_CAVE",
    BOTTOMLESS_SEA = "BOTTOMLESS_SEA",
    BRINE_CAVE = "BRINE_CAVE",
    CONCEALED_RUINS = "CONCEALED_RUINS",
    CRAGGY_COAST = "CRAGGY_COAST",
    CRYSTAL_CAVE_01F_05F = "CRYSTAL_CAVE_01F_05F",
    CRYSTAL_CAVE_06F_11F = "CRYSTAL_CAVE_06F_11F",
    CRYSTAL_CROSSING = "CRYSTAL_CROSSING",
    DARK_CRATER = "DARK_CRATER",
    DEEP_DARK_CRATER = "DEEP_DARK_CRATER",
    DARK_HILL_01F_06F = "DARK_HILL_01F_06F",
    DARK_HILL_07F_15F = "DARK_HILL_07F_15F",
    DEEP_DUSK_FOREST_01F_06F = "DEEP_DUSK_FOREST_01F_06F",
    DEEP_DUSK_FOREST_07F_12F = "DEEP_DUSK_FOREST_07F_12F",
    DEEP_SEALED_RUIN = "DEEP_SEALED_RUIN",
    DRENCHED_BLUFF = "DRENCHED_BLUFF",
    DUSK_FOREST_01F_04F = "DUSK_FOREST_01F_04F",
    DUSK_FOREST_05F_08F = "DUSK_FOREST_05F_08F",
    NORTHERN_DESERT_01F_07F = "NORTHERN_DESERT_01F_07F",
    QUICKSAND_CAVE = "QUICKSAND_CAVE",
    QUICKSAND_PIT = "QUICKSAND_PIT",
    ROCK_AEGIS_CAVE = "ROCK_AEGIS_CAVE",
    SURROUNDED_SEA = "SURROUNDED_SEA",
    TEMPORAL_SPIRE = "TEMPORAL_SPIRE",
    TEMPORAL_TOWER = "TEMPORAL_TOWER",
    TEST_DUNGEON = "TEST_DUNGEON",
    THE_NIGHTMARE = "THE_NIGHTMARE",
    TINY_MEADOW = "TINY_MEADOW",
    TREESHROUD_FOREST_01F_08F = "TREESHROUD_FOREST_01F_08F",
    TREESHROUD_FOREST_09F_21F = "TREESHROUD_FOREST_09F_21F",
    STEAM_CAVE = "STEAM_CAVE",
    QUICKSAND_PIT_2 = "QUICKSAND_PIT_2",
    LOWER_BRINE_CAVE = "LOWER_BRINE_CAVE",
    TEMPORAL_TOWER_2 = "TEMPORAL_TOWER_2",
    CRYSTAL_CAVE_2 = "CRYSTAL_CAVE_2",
    WATERFALL_CAVE = "WATERFALL_CAVE",
    WORLD_ABYSS = "WORLD_ABYSS",
    ZERO_ISLE_EAST_15F_25F = "ZERO_ISLE_EAST_15F_25F",
    ZERO_ISLE_EAST_26F_40F = "ZERO_ISLE_EAST_26F_40F",
    ZERO_ISLE_SOUTH_04F_08F = "ZERO_ISLE_SOUTH_04F_08F",
    ZERO_ISLE_SOUTH_01F_03F = "ZERO_ISLE_SOUTH_01F_03F",
    BURIED_RELIC_1F_20F = "BURIED_RELIC_1F_20F",
    BURIED_RELIC_21F_50F = "BURIED_RELIC_21F_50F",
    BURIED_RELIC_51F_99F = "BURIED_RELIC_51F_99F",
    DARKNIGHT_RELIC = "DARKNIGHT_RELIC",
    SHIMMER_DESERT = "SHIMMER_DESERT",
    UNOWN_RELIC = "UNOWN_RELIC",
    FROSTY_FOREST = "FROSTY_FOREST",
    GREAT_CANYON = "GREAT_CANYON",
    HOWLING_FOREST_01F_06F = "HOWLING_FOREST_01F_06F",
    HOWLING_FOREST_07F_15F = "HOWLING_FOREST_07F_15F",
    MT_FARAWAY = "MT_FARAWAY",
    MT_FARAWAY_10F_20F = "MT_FARAWAY_10F_20F",
    MT_FARAWAY_30F_39F = "MT_FARAWAY_30F_39F",
    JOYOUS_TOWER = "JOYOUS_TOWER",
    LAPIS_CAVE = "LAPIS_CAVE",
    LIGHTNING_FIELD = "LIGHTNING_FIELD",
    MAGMA_CAVERN_08F_17F = "MAGMA_CAVERN_08F_17F",
    MAGMA_CAVERN_18F_23F = "MAGMA_CAVERN_18F_23F",
    METEOR_CAVE = "METEOR_CAVE",
    MT_BLAZE = "MT_BLAZE",
    MT_STEEL_01F_05F = "MT_STEEL_01F_05F",
    MT_STEEL_06F_08F = "MT_STEEL_06F_08F",
    MT_FREEZE = "MT_FREEZE",
    MT_THUNDER_PEAK = "MT_THUNDER_PEAK",
    MT_THUNDER = "MT_THUNDER",
    MURKY_CAVE = "MURKY_CAVE",
    NORMAL_MAZE = "NORMAL_MAZE",
    NORTHERN_RANGE_01F_07F = "NORTHERN_RANGE_01F_07F",
    NORTHERN_RANGE_08F_16F = "NORTHERN_RANGE_08F_16F",
    NORTHWIND_FIELD = "NORTHWIND_FIELD",
    PITFALL_VALLEY = "PITFALL_VALLEY",
    POISON_MAZE = "POISON_MAZE",
    PURITY_FOREST_04F_07F = "PURITY_FOREST_04F_07F",
    PURITY_FOREST_13F_20F = "PURITY_FOREST_13F_20F",
    PURITY_FOREST_30F_43F = "PURITY_FOREST_30F_43F",
    PURITY_FOREST_44F_60F = "PURITY_FOREST_44F_60F",
    PURITY_FOREST_61F_79F = "PURITY_FOREST_61F_79F",
    PURITY_FOREST_80F_99F = "PURITY_FOREST_80F_99F",
    RESCUE_TEAM_MAZE = "RESCUE_TEAM_MAZE",
    ROCK_PATH = "ROCK_PATH",
    SILENT_CHASM = "SILENT_CHASM",
    SILVER_TRENCH = "SILVER_TRENCH",
    SINISTER_WOODS = "SINISTER_WOODS",
    SKY_TOWER = "SKY_TOWER",
    SNOW_PATH = "SNOW_PATH",
    SOLAR_CAVE = "SOLAR_CAVE",
    SOUTHERN_CAVERN_01F_23F = "SOUTHERN_CAVERN_01F_23F",
    SOUTHERN_CAVERN_24F_50F = "SOUTHERN_CAVERN_24F_50F",
    STORMY_SEA_01F_16F = "STORMY_SEA_01F_16F",
    STORMY_SEA_16F_39F = "STORMY_SEA_16F_39F",
    THUNDERWAVE_CAVE = "THUNDERWAVE_CAVE",
    TINY_WOODS = "TINY_WOODS",
    UPROAR_FOREST = "UPROAR_FOREST",
    SERENITY_RIVER = "SERENITY_RIVER",
    WATERFALL_POND = "WATERFALL_POND",
    WESTERN_CAVE_B01F_B27F = "WESTERN_CAVE_B01F_B27F",
    WESTERN_CAVE_B28F_B39F = "WESTERN_CAVE_B28F_B39F",
    WISH_CAVE_01F_13F = "WISH_CAVE_01F_13F",
    WISH_CAVE_90F_99F = "WISH_CAVE_90F_99F",
    WYVERN_HILL = "WYVERN_HILL"
  }

  export type DungeonInfo = {
    id: string
    name: string
    pokemons: Pkm[]
    tileset: Header[]
  }
  

  export const DungeonData: { [key in Dungeon]: DungeonInfo } = Object.freeze({
    FOURTH_STATION_PATH: {
      id: "FOURTH_STATION_PATH",
      name: "4th Station Path",
      pokemons: [],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ]
    },
    SEVEN_STATION_PATH: {
      id: "SEVEN_STATION_PATH",
      name: "7th Station Path",
      pokemons: [],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    BARREN_VALLEY: {
      id: "BARREN_VALLEY",
      name: "Barren Valley",
      pokemons: [],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_ICE_MOUNTAIN_PEAK: {
      id: "DARK_ICE_MOUNTAIN_PEAK",
      name: "Dark Ice Mountain Peak",
      pokemons: [Pkm.GENGAR, Pkm.DUSKULL, Pkm.METANG],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_ICE_MOUNTAIN: {
      id: "DARK_ICE_MOUNTAIN",
      name: "Dark Ice Mountain",
      pokemons: [Pkm.BANETTE, Pkm.GENGAR, Pkm.DUSKULL, Pkm.METANG],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_WASTELAND: {
      id: "DARK_WASTELAND",
      name: "Dark Wasteland",
      pokemons: [Pkm.GASTLY, Pkm.ONIX, Pkm.SHIFTRY],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DEEP_BOULDER_QUARRY: {
      id: "DEEP_BOULDER_QUARRY",
      name: "Deep Boulder Quarry",
      pokemons: [Pkm.NINJASK, Pkm.SHELGON, Pkm.RHYDON, Pkm.METANG, Pkm.STEELIX],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    LIMESTONE_CAVERN: {
      id: "LIMESTONE_CAVERN",
      name: "Limestone Cavern",
      pokemons: [Pkm.MARILL, Pkm.SLOWKING, Pkm.DRAGONAIR],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    DEEP_LIMESTONE_CAVERN: {
      id: "DEEP_LIMESTONE_CAVERN",
      name: "Deep Limestone Cavern",
      pokemons: [Pkm.DRAGONAIR, Pkm.AERODACTYL, Pkm.POLIWHIRL],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    ICICLE_FOREST: {
      id: "ICICLE_FOREST",
      name: "Icicle Forest",
      pokemons: [Pkm.GENGAR, Pkm.CACTURNE, Pkm.METAGROSS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    MURKY_FOREST: {
      id: "MURKY_FOREST",
      name: "Murky Forest",
      pokemons: [Pkm.HOPPIP, Pkm.WEEDLE],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    SPACIAL_CLIFFS: {
      id: "SPACIAL_CLIFFS",
      name: "Spacial Cliffs",
      pokemons: [Pkm.HAUNTER, Pkm.BELDUM, Pkm.SHEDNINJA, Pkm.BANETTE],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TEMPORAL_SPIRE_FUTURE: {
      id: "TEMPORAL_SPIRE_FUTURE",
      name: "Temporal Spire Future",
      pokemons: [
        Pkm.GOLBAT,
        Pkm.ALAKAZAM,
        Pkm.MAGNETON,
        Pkm.GASTLY,
        Pkm.PORYGON_2,
        Pkm.CROBAT
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TEMPORAL_TOWER_FUTURE: {
      id: "TEMPORAL_TOWER_FUTURE",
      name: "Temporal Tower Future",
      pokemons: [Pkm.ZUBAT, Pkm.KADABRA, Pkm.MAGNEMITE, Pkm.GASTLY, Pkm.GOLBAT],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    VAST_ICE_MOUNTAIN_PEAK: {
      id: "VAST_ICE_MOUNTAIN_PEAK",
      name: "Vast Ice Mountain Peak",
      pokemons: [
        Pkm.GENGAR,
        Pkm.AERODACTYL,
        Pkm.DUSCLOPS,
        Pkm.ABSOL,
        Pkm.METAGROSS,
        Pkm.MAGNEZONE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    VAST_ICE_MOUNTAIN: {
      id: "VAST_ICE_MOUNTAIN",
      name: "Vast Ice Mountain",
      pokemons: [
        Pkm.GENGAR,
        Pkm.AERODACTYL,
        Pkm.DUSCLOPS,
        Pkm.ABSOL,
        Pkm.METAGROSS,
        Pkm.MAGNEZONE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    AMP_PLAINS: {
      id: "AMP_PLAINS",
      name: "Amp Plains",
      pokemons: [
        Pkm.MAREEP,
        Pkm.ELEKID,
        Pkm.SHINX,
        Pkm.ZAPDOS,
        Pkm.FLAFFY,
        Pkm.PIKACHU,
        Pkm.PICHU,
        Pkm.ELECTABUZZ
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    FAR_AMP_PLAINS: {
      id: "FAR_AMP_PLAINS",
      name: "Far Amp Plains",
      pokemons: [
        Pkm.SHINX,
        Pkm.PIKACHU,
        Pkm.PICHU,
        Pkm.FLAFFY,
        Pkm.ELECTABUZZ,
        Pkm.ELECTRIKE,
        Pkm.LUXIO,
        Pkm.LUXRAY,
        Pkm.AMPHAROS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    FINAL_MAZE_B23F: {
      id: "FINAL_MAZE_B23F",
      name: "Final Maze",
      pokemons: [
        Pkm.MACHOP,
        Pkm.MAGNEMITE,
        Pkm.OMANYTE,
        Pkm.KABUTO,
        Pkm.MAREEP,
        Pkm.SWINUB,
        Pkm.HOUNDOUR,
        Pkm.MAGBY,
        Pkm.MEDITITE,
        Pkm.BAGON,
        Pkm.STARAVIA,
        Pkm.JIRACHI,
        Pkm.MOLTRES,
        Pkm.SUICUNE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    FOGGY_FOREST: {
      id: "FOGGY_FOREST",
      name: "Foggy Forest",
      pokemons: [Pkm.SKIPLOOM, Pkm.BUNEARY],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    FOREST_PATH: {
      id: "FOREST_PATH",
      name: "Forest Path",
      pokemons: [Pkm.SWINUB, Pkm.HOUNDOUR],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    GOLD_CHAMBER: {
      id: "GOLD_CHAMBER",
      name: "Gold Chamber",
      pokemons: [
        Pkm.MACHOP,
        Pkm.MAGNEMITE,
        Pkm.OMANYTE,
        Pkm.KABUTO,
        Pkm.MAREEP,
        Pkm.SWINUB,
        Pkm.HOUNDOUR,
        Pkm.MAGBY,
        Pkm.MEDITITE,
        Pkm.BAGON,
        Pkm.STARAVIA,
        Pkm.JIRACHI,
        Pkm.MOLTRES,
        Pkm.SUICUNE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    HIDDEN_HIGHLAND: {
      id: "HIDDEN_HIGHLAND",
      name: "Hidden Highland",
      pokemons: [
        Pkm.DRAGONITE,
        Pkm.MANECTRIC,
        Pkm.RAMPARDOS,
        Pkm.BASTIODON,
        Pkm.GARCHOMP,
        Pkm.ABOMASNOW,
        Pkm.MAGMORTAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    MYSTERY_JUNGLE_01F_15F: {
      id: "MYSTERY_JUNGLE_01F_15F",
      name: "Mystery Jungle",
      pokemons: [
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.WALL_ALT_3,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    MYSTERY_JUNGLE_16F_30F: {
      id: "MYSTERY_JUNGLE_16F_30F",
      name: "Mystery Jungle",
      pokemons: [
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    MYSTIFYING_FOREST: {
      id: "MYSTIFYING_FOREST",
      name: "Mystifying Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    BEACH_CAVE: {
      id: "BEACH_CAVE",
      name: "Beach Cave",
      pokemons: [Pkm.KABUTO],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.GROUND_ALT_4,
        Header.WATER
      ],

    },
    BOTTOMLESS_SEA: {
      id: "BOTTOMLESS_SEA",
      name: "Bottomless Sea",
      pokemons: [
        Pkm.KYOGRE,
        Pkm.GYARADOS,
        Pkm.KINGDRA,
        Pkm.SLOWBRO,
        Pkm.HORSEA,
        Pkm.SEADRA,
        Pkm.SLOWKING,
        Pkm.LAPRAS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.WATER
      ],

    },
    BRINE_CAVE: {
      id: "BRINE_CAVE",
      name: "Brine Cave",
      pokemons: [Pkm.OMANYTE, Pkm.DRAGONAIR],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CONCEALED_RUINS: {
      id: "CONCEALED_RUINS",
      name: "Concealed Ruins",
      pokemons: [
        Pkm.PIDGEY,
        Pkm.LOUDRED,
        Pkm.NIDOQUEEN,
        Pkm.SHUPPET,
        Pkm.RAIKOU,
        Pkm.PIDGEOT
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CRAGGY_COAST: {
      id: "CRAGGY_COAST",
      name: "Craggy Coast",
      pokemons: [Pkm.SPHEAL, Pkm.DRATINI, Pkm.SEALEO],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CRYSTAL_CAVE_01F_05F: {
      id: "CRYSTAL_CAVE_01F_05F",
      name: "Crystal Cave",
      pokemons: [Pkm.GRAVELER, Pkm.BELDUM, Pkm.CRANIDOS, Pkm.SHIELDON, Pkm.GOLEM],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CRYSTAL_CAVE_06F_11F: {
      id: "CRYSTAL_CAVE_06F_11F",
      name: "Crystal Cave",
      pokemons: [Pkm.GRAVELER, Pkm.BELDUM, Pkm.CRANIDOS, Pkm.SHIELDON, Pkm.GOLEM],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CRYSTAL_CROSSING: {
      id: "CRYSTAL_CROSSING",
      name: "Crystal Crossing",
      pokemons: [Pkm.BAGON, Pkm.ABSOL, Pkm.GLALIE, Pkm.FROSLASS, Pkm.AZELF],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_CRATER: {
      id: "DARK_CRATER",
      name: "Dark Crater",
      pokemons: [
        Pkm.CHARMANDER,
        Pkm.CYNDAQUIL,
        Pkm.NUMEL,
        Pkm.GROWLITHE,
        Pkm.PONYTA,
        Pkm.TORCHIC,
        Pkm.FLAREON,
        Pkm.COMBUSKEN,
        Pkm.RAPIDASH,
        Pkm.MEWTWO,
        Pkm.ARCANINE,
        Pkm.QUILAVA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DEEP_DARK_CRATER: {
      id: "DEEP_DARK_CRATER",
      name: "Deep Dark Crater",
      pokemons: [
        Pkm.CHARMELEON,
        Pkm.QUILAVA,
        Pkm.MONFERNO,
        Pkm.CAMERUPT,
        Pkm.COMBUSKEN,
        Pkm.ARCANINE,
        Pkm.RAPIDASH,
        Pkm.FLAREON,
        Pkm.RHYPERIOR,
        Pkm.MAGMORTAR,
        Pkm.CHARIZARD,
        Pkm.TYPHLOSION,
        Pkm.INFERNAPE,
        Pkm.BLAZIKEN,
        Pkm.AGGRON,
        Pkm.ENTEI
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_HILL_01F_06F: {
      id: "DARK_HILL_01F_06F",
      name: "Dark Hill",
      pokemons: [Pkm.GASTLY, Pkm.HAUNTER, Pkm.GENGAR, Pkm.BANETTE, Pkm.DUSCLOPS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARK_HILL_07F_15F: {
      id: "DARK_HILL_07F_15F",
      name: "Dark Hill",
      pokemons: [Pkm.GASTLY, Pkm.HAUNTER, Pkm.GENGAR, Pkm.BANETTE, Pkm.DUSCLOPS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DEEP_DUSK_FOREST_01F_06F: {
      id: "DEEP_DUSK_FOREST_01F_06F",
      name: "Deep Dusk Forest",
      pokemons: [Pkm.RHYDON, Pkm.STEELIX, Pkm.AGGRON, Pkm.LEAFEON],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DEEP_DUSK_FOREST_07F_12F: {
      id: "DEEP_DUSK_FOREST_07F_12F",
      name: "Deep Dusk Forest",
      pokemons: [Pkm.RHYDON, Pkm.STEELIX, Pkm.AGGRON, Pkm.LEAFEON],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DEEP_SEALED_RUIN: {
      id: "DEEP_SEALED_RUIN",
      name: "Deep Sealed Ruin",
      pokemons: [Pkm.SHELGON, Pkm.METANG],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DRENCHED_BLUFF: {
      id: "DRENCHED_BLUFF",
      name: "Drenched Bluff",
      pokemons: [Pkm.LILEEP, Pkm.ANORITH],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DUSK_FOREST_01F_04F: {
      id: "DUSK_FOREST_01F_04F",
      name: "Dusk Forest",
      pokemons: [
        Pkm.JUMPLUFF,
        Pkm.GABITE,
        Pkm.HAUNTER,
        Pkm.SALAMENCE,
        Pkm.RHYPERIOR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DUSK_FOREST_05F_08F: {
      id: "DUSK_FOREST_05F_08F",
      name: "Dusk Forest",
      pokemons: [
        Pkm.JUMPLUFF,
        Pkm.GABITE,
        Pkm.HAUNTER,
        Pkm.SALAMENCE,
        Pkm.RHYPERIOR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    NORTHERN_DESERT_01F_07F: {
      id: "NORTHERN_DESERT_01F_07F",
      name: "Northern Desert",
      pokemons: [
        Pkm.CUBONE,
        Pkm.ARON,
        Pkm.CACNEA,
        Pkm.LARVITAR,
        Pkm.TRAPINCH,
        Pkm.RHYHORN,
        Pkm.LAIRON,
        Pkm.CACTURNE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    QUICKSAND_CAVE: {
      id: "QUICKSAND_CAVE",
      name: "Quicksand Cave",
      pokemons: [Pkm.NINCADA, Pkm.VIBRAVA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    QUICKSAND_PIT: {
      id: "QUICKSAND_PIT",
      name: "Quicksand Pit",
      pokemons: [Pkm.MESPRIT, Pkm.TYRANITAR, Pkm.NINJASK],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    ROCK_AEGIS_CAVE: {
      id: "ROCK_AEGIS_CAVE",
      name: "Rock Aegis Cave",
      pokemons: [Pkm.ZUBAT, Pkm.GOLBAT, Pkm.MACHOKE, Pkm.MACHAMP, Pkm.REGIROCK],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    SURROUNDED_SEA: {
      id: "SURROUNDED_SEA",
      name: "Surrounded Sea",
      pokemons: [
        Pkm.CARVANHA,
        Pkm.SLOWBRO,
        Pkm.HORSEA,
        Pkm.SEADRA,
        Pkm.SLOWKING,
        Pkm.KINGDRA,
        Pkm.LAPRAS,
        Pkm.LUGIA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.WATER
      ],

    },
    TEMPORAL_SPIRE: {
      id: "TEMPORAL_SPIRE",
      name: "Temporal Spire",
      pokemons: [
        Pkm.DIALGA,
        Pkm.DEOXYS,
        Pkm.PORYGON,
        Pkm.SALAMENCE,
        Pkm.PORYGON_Z,
        Pkm.METAGROSS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TEMPORAL_TOWER: {
      id: "TEMPORAL_TOWER",
      name: "Temporal Tower",
      pokemons: [Pkm.PORYGON],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TEST_DUNGEON: {
      id: "TEST_DUNGEON",
      name: "Test Dungeon",
      pokemons: [Pkm.PORYGON],
      tileset: [Header.WALL, Header.WALL_ALT_1, Header.GROUND, Header.WATER],

    },
    THE_NIGHTMARE: {
      id: "THE_NIGHTMARE",
      name: "The Nightmare",
      pokemons: [
        Pkm.CLEFFA,
        Pkm.CLEFAIRY,
        Pkm.JIGGLYPUFF,
        Pkm.ESPEON,
        Pkm.WHISMUR,
        Pkm.PERSIAN,
        Pkm.IGGLYBUFF,
        Pkm.CLEFABLE,
        Pkm.WIGGLYTUFF
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TINY_MEADOW: {
      id: "TINY_MEADOW",
      name: "Tiny Meadow",
      pokemons: [Pkm.SKIPLOOM, Pkm.STARAVIA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TREESHROUD_FOREST_01F_08F: {
      id: "TREESHROUD_FOREST_01F_08F",
      name: "Treeshroud Forest",
      pokemons: [Pkm.KADABRA, Pkm.RALTS, Pkm.ALAKAZAM, Pkm.KIRLIA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TREESHROUD_FOREST_09F_21F: {
      id: "TREESHROUD_FOREST_09F_21F",
      name: "Treeshroud Forest",
      pokemons: [Pkm.KADABRA, Pkm.RALTS, Pkm.ALAKAZAM, Pkm.KIRLIA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    STEAM_CAVE: {
      id: "STEAM_CAVE",
      name: "Steam Cave",
      pokemons: [Pkm.MAGBY, Pkm.NUMEL],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    QUICKSAND_PIT_2: {
      id: "QUICKSAND_PIT_2",
      name: "Quicksand Pit",
      pokemons: [Pkm.MESPRIT, Pkm.TYRANITAR, Pkm.NINJASK],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    LOWER_BRINE_CAVE: {
      id: "LOWER_BRINE_CAVE",
      name: "Lower Brine Cave",
      pokemons: [Pkm.WALREIN, Pkm.DRAGONAIR],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    HIDDEN_LAND: {
      id: "HIDDEN_LAND",
      name: "Hidden land",
      pokemons: [
        Pkm.DRAGONITE,
        Pkm.MANECTRIC,
        Pkm.RAMPARDOS,
        Pkm.BASTIODON,
        Pkm.GARCHOMP,
        Pkm.ABOMASNOW,
        Pkm.MAGMORTAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TEMPORAL_TOWER_2: {
      id: "TEMPORAL_TOWER_2",
      name: "Temporal Tower",
      pokemons: [Pkm.PORYGON],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    CRYSTAL_CAVE_2: {
      id: "CRYSTAL_CAVE_2",
      name: "Crystal Cave",
      pokemons: [Pkm.GRAVELER, Pkm.BELDUM, Pkm.CRANIDOS, Pkm.SHIELDON, Pkm.GOLEM],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    WATERFALL_CAVE: {
      id: "WATERFALL_CAVE",
      name: "Waterfall Cave",
      pokemons: [Pkm.POLIWAG, Pkm.LOTAD],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    WORLD_ABYSS: {
      id: "WORLD_ABYSS",
      name: "World Abyss",
      pokemons: [
        Pkm.GIRATINA,
        Pkm.PIDGEY,
        Pkm.LOUDRED,
        Pkm.NIDOQUEEN,
        Pkm.UMBREON,
        Pkm.PIDGEOT
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    ZERO_ISLE_EAST_15F_25F: {
      id: "ZERO_ISLE_EAST_15F_25F",
      name: "Zero Isle East",
      pokemons: [
        Pkm.KABUTO,
        Pkm.AZUMARILL,
        Pkm.SLOWPOKE,
        Pkm.SPEAROW,
        Pkm.SEEDOT,
        Pkm.GOLBAT,
        Pkm.HOUNDOUR,
        Pkm.MAGNETON,
        Pkm.BEEDRILL,
        Pkm.FERALIGATR,
        Pkm.MAGMAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    ZERO_ISLE_EAST_26F_40F: {
      id: "ZERO_ISLE_EAST_26F_40F",
      name: "Zero Isle East",
      pokemons: [
        Pkm.KABUTO,
        Pkm.AZUMARILL,
        Pkm.SLOWPOKE,
        Pkm.SPEAROW,
        Pkm.SEEDOT,
        Pkm.GOLBAT,
        Pkm.HOUNDOUR,
        Pkm.MAGNETON,
        Pkm.BEEDRILL,
        Pkm.FERALIGATR,
        Pkm.MAGMAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    ZERO_ISLE_SOUTH_01F_03F: {
      id: "ZERO_ISLE_SOUTH_01F_03F",
      name: "Zero Isle South",
      pokemons: [
        Pkm.PIDGEY,
        Pkm.JIGGLYPUFF,
        Pkm.SEADRA,
        Pkm.CLEFFA,
        Pkm.BELLSPROUT,
        Pkm.NIDORANM,
        Pkm.LARVITAR,
        Pkm.RATTATA,
        Pkm.TOGEPI,
        Pkm.EEVEE,
        Pkm.RALTS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    ZERO_ISLE_SOUTH_04F_08F: {
      id: "ZERO_ISLE_SOUTH_04F_08F",
      name: "Zero Isle East",
      pokemons: [
        Pkm.PIDGEY,
        Pkm.JIGGLYPUFF,
        Pkm.SEADRA,
        Pkm.CLEFFA,
        Pkm.BELLSPROUT,
        Pkm.NIDORANM,
        Pkm.LARVITAR,
        Pkm.RATTATA,
        Pkm.TOGEPI,
        Pkm.EEVEE,
        Pkm.RALTS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    BURIED_RELIC_1F_20F: {
      id: "BURIED_RELIC_1F_20F",
      name: "Buried Relic",
      pokemons: [
        Pkm.GOLBAT,
        Pkm.RATICATE,
        Pkm.MACHOP,
        Pkm.WHISMUR,
        Pkm.PORYGON,
        Pkm.PORYGON_2,
        Pkm.ARON,
        Pkm.REGIROCK,
        Pkm.GEODUDE,
        Pkm.REGISTEEL,
        Pkm.REGICE,
        Pkm.KADABRA,
        Pkm.SHEDNINJA,
        Pkm.GRAVELER,
        Pkm.HAUNTER,
        Pkm.GOLEM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    BURIED_RELIC_21F_50F: {
      id: "BURIED_RELIC_21F_50F",
      name: "Buried Relic",
      pokemons: [
        Pkm.GOLBAT,
        Pkm.RATICATE,
        Pkm.MACHOP,
        Pkm.WHISMUR,
        Pkm.PORYGON,
        Pkm.PORYGON_2,
        Pkm.ARON,
        Pkm.REGIROCK,
        Pkm.GEODUDE,
        Pkm.REGISTEEL,
        Pkm.REGICE,
        Pkm.KADABRA,
        Pkm.SHEDNINJA,
        Pkm.GRAVELER,
        Pkm.HAUNTER,
        Pkm.GOLEM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    BURIED_RELIC_51F_99F: {
      id: "BURIED_RELIC_51F_99F",
      name: "Buried Relic",
      pokemons: [
        Pkm.GOLBAT,
        Pkm.RATICATE,
        Pkm.MACHOP,
        Pkm.WHISMUR,
        Pkm.PORYGON,
        Pkm.PORYGON_2,
        Pkm.ARON,
        Pkm.REGIROCK,
        Pkm.GEODUDE,
        Pkm.REGISTEEL,
        Pkm.REGICE,
        Pkm.KADABRA,
        Pkm.SHEDNINJA,
        Pkm.GRAVELER,
        Pkm.HAUNTER,
        Pkm.GOLEM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    DARKNIGHT_RELIC: {
      id: "DARKNIGHT_RELIC",
      name: "Darknight Relic",
      pokemons: [
        Pkm.SHUPPET,
        Pkm.GASTLY,
        Pkm.SHEDNINJA,
        Pkm.BANETTE,
        Pkm.HAUNTER,
        Pkm.DUSKULL,
        Pkm.GENGAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    SHIMMER_DESERT: {
      id: "SHIMMER_DESERT",
      name: "Shimmer Desert",
      pokemons: [Pkm.NIDOKING, Pkm.GARCHOMP, Pkm.RHYPERIOR, Pkm.GROUDON],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    UNOWN_RELIC: {
      id: "UNOWN_RELIC",
      name: "Unown Relic",
      pokemons: [],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    FROSTY_FOREST: {
      id: "FROSTY_FOREST",
      name: "Frosty Forest",
      pokemons: [
        Pkm.AZURILL,
        Pkm.PILOSWINE,
        Pkm.LAIRON,
        Pkm.SNORUNT,
        Pkm.ARTICUNO
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    GREAT_CANYON: {
      id: "GREAT_CANYON",
      name: "Great Canyon",
      pokemons: [Pkm.SKIPLOOM, Pkm.VILEPLUME, Pkm.CACTURNE],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    HOWLING_FOREST_01F_06F: {
      id: "HOWLING_FOREST_01F_06F",
      name: "Howling Forest",
      pokemons: [
        Pkm.AZURILL,
        Pkm.HOUNDOUR,
        Pkm.WHISMUR,
        Pkm.PIDGEY,
        Pkm.LOUDRED,
        Pkm.SNORLAX
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    HOWLING_FOREST_07F_15F: {
      id: "HOWLING_FOREST_07F_15F",
      name: "Howling Forest",
      pokemons: [
        Pkm.AZURILL,
        Pkm.HOUNDOUR,
        Pkm.WHISMUR,
        Pkm.PIDGEY,
        Pkm.LOUDRED,
        Pkm.SNORLAX
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_FARAWAY: {
      id: "MT_FARAWAY",
      name: "Mt Faraway",
      pokemons: [
        Pkm.SNORUNT,
        Pkm.AZUMARILL,
        Pkm.GOLEM,
        Pkm.MARSHTOMP,
        Pkm.VIGOROTH,
        Pkm.GLALIE,
        Pkm.HO_OH
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_FARAWAY_10F_20F: {
      id: "MT_FARAWAY_10F_20F",
      name: "Mt Faraway",
      pokemons: [
        Pkm.SNORUNT,
        Pkm.AZUMARILL,
        Pkm.GOLEM,
        Pkm.MARSHTOMP,
        Pkm.VIGOROTH,
        Pkm.GLALIE,
        Pkm.HO_OH
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_FARAWAY_30F_39F: {
      id: "MT_FARAWAY_30F_39F",
      name: "Mt Faraway",
      pokemons: [
        Pkm.SNORUNT,
        Pkm.AZUMARILL,
        Pkm.GOLEM,
        Pkm.MARSHTOMP,
        Pkm.VIGOROTH,
        Pkm.GLALIE,
        Pkm.HO_OH
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    JOYOUS_TOWER: {
      id: "JOYOUS_TOWER",
      name: "Joyous Tower",
      pokemons: [
        Pkm.JIGGLYPUFF,
        Pkm.TREECKO,
        Pkm.BULBASAUR,
        Pkm.PICHU,
        Pkm.METAPOD,
        Pkm.CHIKORITA,
        Pkm.KAKUNA,
        Pkm.CLEFAIRY,
        Pkm.TORCHIC,
        Pkm.EEVEE,
        Pkm.CYNDAQUIL,
        Pkm.BELDUM,
        Pkm.SCYTHER,
        Pkm.SLAKOTH,
        Pkm.TRAPINCH,
        Pkm.CLEFABLE,
        Pkm.HOUNDOUR,
        Pkm.GARDEVOIR,
        Pkm.BELLOSSOM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    LAPIS_CAVE: {
      id: "LAPIS_CAVE",
      name: "Lapis Cave",
      pokemons: [
        Pkm.ZUBAT,
        Pkm.NINCADA,
        Pkm.NIDORINA,
        Pkm.NIDORINO,
        Pkm.BAGON,
        Pkm.GOLBAT
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    LIGHTNING_FIELD: {
      id: "LIGHTNING_FIELD",
      name: "Lightning Field",
      pokemons: [
        Pkm.MAREEP,
        Pkm.ELECTRIKE,
        Pkm.MAGNEMITE,
        Pkm.PIKACHU,
        Pkm.FLAFFY,
        Pkm.JOLTEON,
        Pkm.CACTURNE,
        Pkm.ELEKID,
        Pkm.MAGNETON,
        Pkm.AMPHAROS,
        Pkm.MANECTRIC,
        Pkm.RAICHU,
        Pkm.RAIKOU
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    MAGMA_CAVERN_08F_17F: {
      id: "MAGMA_CAVERN_08F_17F",
      name: "Magma Cavern",
      pokemons: [
        Pkm.RATICATE,
        Pkm.NIDOQUEEN,
        Pkm.NIDOKING,
        Pkm.GRAVELER,
        Pkm.MAGMAR,
        Pkm.GOLEM,
        Pkm.ONIX
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    MAGMA_CAVERN_18F_23F: {
      id: "MAGMA_CAVERN_18F_23F",
      name: "Magma Cavern",
      pokemons: [
        Pkm.GROUDON,
        Pkm.RATICATE,
        Pkm.NIDOQUEEN,
        Pkm.NIDOKING,
        Pkm.GRAVELER,
        Pkm.MAGMAR,
        Pkm.GOLEM,
        Pkm.ONIX
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    METEOR_CAVE: {
      id: "METEOR_CAVE",
      name: "Meteor Cave",
      pokemons: [Pkm.DEOXYS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    MT_BLAZE: {
      id: "MT_BLAZE",
      name: "Mt Blaze",
      pokemons: [
        Pkm.PIDGEOT,
        Pkm.MAGBY,
        Pkm.NUMEL,
        Pkm.RAPIDASH,
        Pkm.FEAROW,
        Pkm.ARCANINE,
        Pkm.MOLTRES
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    MT_STEEL_01F_05F: {
      id: "MT_STEEL_01F_05F",
      name: "Mt Steel",
      pokemons: [Pkm.SPEAROW, Pkm.ARON, Pkm.GEODUDE, Pkm.MEDITITE, Pkm.BELDUM],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_STEEL_06F_08F: {
      id: "MT_STEEL_06F_08F",
      name: "Mt Steel",
      pokemons: [Pkm.SPEAROW, Pkm.ARON, Pkm.GEODUDE, Pkm.MEDITITE, Pkm.BELDUM],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_FREEZE: {
      id: "MT_FREEZE",
      name: "Mt Freeze",
      pokemons: [Pkm.SWABLU, Pkm.SHELGON, Pkm.VIGOROTH, Pkm.SLAKING],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_THUNDER_PEAK: {
      id: "MT_THUNDER_PEAK",
      name: "Mt Thunder Peak",
      pokemons: [
        Pkm.WEEDLE,
        Pkm.NIDORANM,
        Pkm.ELECTRIKE,
        Pkm.CACNEA,
        Pkm.BEEDRILL,
        Pkm.ELECTABUZZ,
        Pkm.AMPHAROS,
        Pkm.MANECTRIC,
        Pkm.GROWLITHE,
        Pkm.ZAPDOS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    MT_THUNDER: {
      id: "MT_THUNDER",
      name: "Mt Thunder",
      pokemons: [
        Pkm.WEEDLE,
        Pkm.NIDORANM,
        Pkm.ELECTRIKE,
        Pkm.CACNEA,
        Pkm.BEEDRILL,
        Pkm.ELECTABUZZ,
        Pkm.AMPHAROS,
        Pkm.MANECTRIC,
        Pkm.GROWLITHE,
        Pkm.ZAPDOS
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    MURKY_CAVE: {
      id: "MURKY_CAVE",
      name: "Murky Cave",
      pokemons: [Pkm.ZUBAT, Pkm.GOLBAT, Pkm.SHEDNINJA, Pkm.SHUPPET, Pkm.CROBAT],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    NORMAL_MAZE: {
      id: "NORMAL_MAZE",
      name: "Normal Maze",
      pokemons: [Pkm.RATICATE],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    NORTHERN_RANGE_01F_07F: {
      id: "NORTHERN_RANGE_01F_07F",
      name: "Northern Range",
      pokemons: [Pkm.NINJASK, Pkm.PIDGEOT, Pkm.FEAROW, Pkm.TOGETIC, Pkm.LATIOS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    NORTHERN_RANGE_08F_16F: {
      id: "NORTHERN_RANGE_08F_16F",
      name: "Northern Range",
      pokemons: [Pkm.NINJASK, Pkm.PIDGEOT, Pkm.FEAROW, Pkm.TOGETIC, Pkm.LATIOS],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    NORTHWIND_FIELD: {
      id: "NORTHWIND_FIELD",
      name: "Northwind Field",
      pokemons: [
        Pkm.AZUMARILL,
        Pkm.VAPOREON,
        Pkm.POLIWHIRL,
        Pkm.POLITOED,
        Pkm.ABSOL,
        Pkm.CROCONAW,
        Pkm.WARTORTLE,
        Pkm.SUICUNE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PITFALL_VALLEY: {
      id: "PITFALL_VALLEY",
      name: "Pitfall Valley",
      pokemons: [
        Pkm.PIDGEOT,
        Pkm.HOPPIP,
        Pkm.BUTTERFREE,
        Pkm.RATICATE,
        Pkm.SWABLU,
        Pkm.SKIPLOOM,
        Pkm.AERODACTYL
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    POISON_MAZE: {
      id: "POISON_MAZE",
      name: "Poison Maze",
      pokemons: [Pkm.NIDORANF, Pkm.NIDORANM, Pkm.NIDORINO, Pkm.NIDORINA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    PURITY_FOREST_04F_07F: {
      id: "PURITY_FOREST_04F_07F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PURITY_FOREST_13F_20F: {
      id: "PURITY_FOREST_13F_20F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PURITY_FOREST_30F_43F: {
      id: "PURITY_FOREST_30F_43F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PURITY_FOREST_44F_60F: {
      id: "PURITY_FOREST_44F_60F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PURITY_FOREST_61F_79F: {
      id: "PURITY_FOREST_61F_79F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    PURITY_FOREST_80F_99F: {
      id: "PURITY_FOREST_80F_99F",
      name: "Purity Forest",
      pokemons: [
        Pkm.CELEBI,
        Pkm.DARKRAI,
        Pkm.BULBASAUR,
        Pkm.IVYSAUR,
        Pkm.VENUSAUR,
        Pkm.METAPOD,
        Pkm.RATTATA,
        Pkm.RATICATE,
        Pkm.SPEAROW,
        Pkm.NIDORANF,
        Pkm.NIDORANM,
        Pkm.VILEPLUME,
        Pkm.BELLSPROUT,
        Pkm.WEEPINBELL,
        Pkm.VICTREEBEL,
        Pkm.SCYTHER,
        Pkm.CHIKORITA,
        Pkm.BAYLEEF,
        Pkm.MEGANIUM,
        Pkm.TREECKO,
        Pkm.GROVYLE,
        Pkm.SCEPTILE,
        Pkm.SEEDOT,
        Pkm.NUZLEAF,
        Pkm.ROSELIA,
        Pkm.FLYGON,
        Pkm.MUNCHLAX,
        Pkm.TURTWIG,
        Pkm.GROTLE,
        Pkm.TORTERRA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    RESCUE_TEAM_MAZE: {
      id: "RESCUE_TEAM_MAZE",
      name: "Rescue Team Maze",
      pokemons: [Pkm.PIDGEY, Pkm.RATTATA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    ROCK_PATH: {
      id: "ROCK_PATH",
      name: "Rock Path",
      pokemons: [Pkm.PIDGEOT, Pkm.NIDORINA, Pkm.NIDORINO, Pkm.ZUBAT, Pkm.NUMEL],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    SILENT_CHASM: {
      id: "SILENT_CHASM",
      name: "Silent Chasm",
      pokemons: [
        Pkm.WEEDLE,
        Pkm.GLOOM,
        Pkm.HOUNDOUR,
        Pkm.POLIWAG,
        Pkm.TRAPINCH,
        Pkm.BEEDRILL
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    SILVER_TRENCH: {
      id: "SILVER_TRENCH",
      name: "Silver Trench",
      pokemons: [
        Pkm.LUGIA,
        Pkm.KABUTO,
        Pkm.AZUMARILL,
        Pkm.SLOWPOKE,
        Pkm.SPEAROW,
        Pkm.SEEDOT,
        Pkm.GOLBAT,
        Pkm.HOUNDOUR,
        Pkm.MAGNETON,
        Pkm.BEEDRILL,
        Pkm.FERALIGATR,
        Pkm.MAGMAR
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.WATER
      ],

    },
    SINISTER_WOODS: {
      id: "SINISTER_WOODS",
      name: "Sinister Woods",
      pokemons: [
        Pkm.SWINUB,
        Pkm.ODDISH,
        Pkm.SCYTHER,
        Pkm.SLAKOTH,
        Pkm.GENGAR,
        Pkm.MEDICHAM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    SKY_TOWER: {
      id: "SKY_TOWER",
      name: "Sky Tower",
      pokemons: [
        Pkm.SHEDNINJA,
        Pkm.SHUPPET,
        Pkm.RAYQUAZA,
        Pkm.DUSKULL,
        Pkm.ALTARIA,
        Pkm.SCIZOR,
        Pkm.DUSCLOPS,
        Pkm.FLYGON
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    SNOW_PATH: {
      id: "SNOW_PATH",
      name: "Snow Path",
      pokemons: [Pkm.AZURILL],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    SOLAR_CAVE: {
      id: "SOLAR_CAVE",
      name: "Solar Cave",
      pokemons: [
        Pkm.BELDUM,
        Pkm.ABRA,
        Pkm.MEDITITE,
        Pkm.METANG,
        Pkm.KIRLIA,
        Pkm.KADABRA,
        Pkm.MEDICHAM
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    SOUTHERN_CAVERN_01F_23F: {
      id: "SOUTHERN_CAVERN_01F_23F",
      name: "Southern Cavern",
      pokemons: [
        Pkm.GEODUDE,
        Pkm.SEEDOT,
        Pkm.CUBONE,
        Pkm.NIDOKING,
        Pkm.VIBRAVA,
        Pkm.LARVITAR,
        Pkm.MAROWAK,
        Pkm.GRAVELER,
        Pkm.RHYHORN,
        Pkm.FLYGON,
        Pkm.GOLEM,
        Pkm.ONIX,
        Pkm.RHYDON
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    SOUTHERN_CAVERN_24F_50F: {
      id: "SOUTHERN_CAVERN_24F_50F",
      name: "Southern Cavern",
      pokemons: [
        Pkm.GEODUDE,
        Pkm.SEEDOT,
        Pkm.CUBONE,
        Pkm.NIDOKING,
        Pkm.VIBRAVA,
        Pkm.LARVITAR,
        Pkm.MAROWAK,
        Pkm.GRAVELER,
        Pkm.RHYHORN,
        Pkm.FLYGON,
        Pkm.GOLEM,
        Pkm.ONIX,
        Pkm.RHYDON
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    STORMY_SEA_01F_16F: {
      id: "STORMY_SEA_01F_16F",
      name: "Stormy Sea",
      pokemons: [
        Pkm.OMANYTE,
        Pkm.OMASTAR,
        Pkm.SLOWPOKE,
        Pkm.SPHEAL,
        Pkm.OMASTAR,
        Pkm.KABUTOPS,
        Pkm.ARMALDO,
        Pkm.SEADRA,
        Pkm.SEALEO,
        Pkm.KYOGRE,
        Pkm.CARVANHA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.WATER
      ],

    },
    STORMY_SEA_16F_39F: {
      id: "STORMY_SEA_16F_39F",
      name: "Stormy Sea",
      pokemons: [
        Pkm.OMANYTE,
        Pkm.OMASTAR,
        Pkm.SLOWPOKE,
        Pkm.SPHEAL,
        Pkm.OMASTAR,
        Pkm.KABUTOPS,
        Pkm.ARMALDO,
        Pkm.SEADRA,
        Pkm.SEALEO,
        Pkm.KYOGRE,
        Pkm.CARVANHA
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.WATER
      ],

    },
    THUNDERWAVE_CAVE: {
      id: "THUNDERWAVE_CAVE",
      name: "Thunderwave Cave",
      pokemons: [Pkm.RATTATA, Pkm.NIDORANM, Pkm.ELEKID],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    TINY_WOODS: {
      id: "TINY_WOODS",
      name: "Tiny Woods",
      pokemons: [Pkm.RATTATA, Pkm.RATTATA],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    UPROAR_FOREST: {
      id: "UPROAR_FOREST",
      name: "Uproar Forest",
      pokemons: [Pkm.ROSELIA, Pkm.NUZLEAF, Pkm.LOTAD, Pkm.RATICATE],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.WATER
      ],

    },
    SERENITY_RIVER: {
      id: "SERENITY_RIVER",
      name: "Serenity River",
      pokemons: [Pkm.POLIWAG, Pkm.LOTAD],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    WATERFALL_POND: {
      id: "WATERFALL_POND",
      name: "Waterfall Pond",
      pokemons: [
        Pkm.MUDKIP,
        Pkm.LOTAD,
        Pkm.POLIWAG,
        Pkm.TOTODILE,
        Pkm.MAGIKARP,
        Pkm.SQUIRTLE,
        Pkm.LOMBRE,
        Pkm.MARSHTOMP
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    WESTERN_CAVE_B01F_B27F: {
      id: "WESTERN_CAVE_B01F_B27F",
      name: "Western Cave",
      pokemons: [
        Pkm.BUTTERFREE,
        Pkm.MEOWTH,
        Pkm.BELLOSSOM,
        Pkm.IGGLYBUFF,
        Pkm.ESPEON,
        Pkm.IVYSAUR,
        Pkm.AGGRON,
        Pkm.PERSIAN,
        Pkm.BAYLEEF,
        Pkm.ALAKAZAM,
        Pkm.TYRANITAR,
        Pkm.SCEPTILE,
        Pkm.ARCANINE,
        Pkm.SWAMPERT,
        Pkm.MACHAMP,
        Pkm.STEELIX,
        Pkm.CHARIZARD,
        Pkm.BLASTOISE,
        Pkm.MEWTWO
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    WESTERN_CAVE_B28F_B39F: {
      id: "WESTERN_CAVE_B28F_B39F",
      name: "Western Cave",
      pokemons: [
        Pkm.BUTTERFREE,
        Pkm.MEOWTH,
        Pkm.BELLOSSOM,
        Pkm.IGGLYBUFF,
        Pkm.ESPEON,
        Pkm.IVYSAUR,
        Pkm.AGGRON,
        Pkm.PERSIAN,
        Pkm.BAYLEEF,
        Pkm.ALAKAZAM,
        Pkm.TYRANITAR,
        Pkm.SCEPTILE,
        Pkm.ARCANINE,
        Pkm.SWAMPERT,
        Pkm.MACHAMP,
        Pkm.STEELIX,
        Pkm.CHARIZARD,
        Pkm.BLASTOISE,
        Pkm.MEWTWO
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    WISH_CAVE_01F_13F: {
      id: "WISH_CAVE_01F_13F",
      name: "Wish Cave",
      pokemons: [
        Pkm.BUTTERFREE,
        Pkm.MEOWTH,
        Pkm.BELLOSSOM,
        Pkm.IGGLYBUFF,
        Pkm.ESPEON,
        Pkm.IVYSAUR,
        Pkm.AGGRON,
        Pkm.PERSIAN,
        Pkm.BAYLEEF,
        Pkm.ALAKAZAM,
        Pkm.TYRANITAR,
        Pkm.SCEPTILE,
        Pkm.ARCANINE,
        Pkm.SWAMPERT,
        Pkm.MACHAMP,
        Pkm.STEELIX,
        Pkm.CHARIZARD,
        Pkm.BLASTOISE,
        Pkm.JIRACHI
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.GROUND_ALT_3,
        Header.WATER
      ],

    },
    WISH_CAVE_90F_99F: {
      id: "WISH_CAVE_90F_99F",
      name: "Wish Cave",
      pokemons: [
        Pkm.BUTTERFREE,
        Pkm.MEOWTH,
        Pkm.BELLOSSOM,
        Pkm.IGGLYBUFF,
        Pkm.ESPEON,
        Pkm.IVYSAUR,
        Pkm.AGGRON,
        Pkm.PERSIAN,
        Pkm.BAYLEEF,
        Pkm.ALAKAZAM,
        Pkm.TYRANITAR,
        Pkm.SCEPTILE,
        Pkm.ARCANINE,
        Pkm.SWAMPERT,
        Pkm.MACHAMP,
        Pkm.STEELIX,
        Pkm.CHARIZARD,
        Pkm.BLASTOISE,
        Pkm.JIRACHI
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    },
    WYVERN_HILL: {
      id: "WYVERN_HILL",
      name: "Wyvern Hill",
      pokemons: [
        Pkm.BAGON,
        Pkm.DRATINI,
        Pkm.ALTARIA,
        Pkm.TOTODILE,
        Pkm.LUDICOLO,
        Pkm.SHELGON,
        Pkm.VIBRAVA,
        Pkm.DRAGONAIR,
        Pkm.SALAMENCE,
        Pkm.FLYGON,
        Pkm.DRAGONITE
      ],
      tileset: [
        Header.WALL,
        Header.WALL_ALT_1,
        Header.WALL_ALT_2,
        Header.GROUND,
        Header.GROUND_ALT_1,
        Header.GROUND_ALT_2,
        Header.WATER
      ],

    }
  })
